apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    name: deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: 046402772087.dkr.ecr.us-east-1.amazonaws.com/matt/jenkins-handson:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE_HOST
          value: service-db.default.svc.cluster.local
        - name: MYSQL_DATABASE_USER
          value: clarusway
        - name: MYSQL_DATABASE_PASSWORD
          value: Clarusway
        - name: MYSQL_DATABASE_DB
          value: phonebook
        - name: MYSQL_DATABASE_PORT
          value: "3306"